# Generated by Django 5.1.5 on 2025-10-08 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('p2p_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('pending', 'В ожидании'), ('completed', 'Завершена')], default='active', max_length=20)),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.user')),
            ],
            options={
                'db_table': 'bids',
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершенная'), ('canceled', 'Отмененная'), ('expired', 'Просроченная')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
                ('wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.depwallet')),
            ],
            options={
                'db_table': 'deposit_requests',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('tinkoff', 'Тинькофф'), ('sber', 'Сбербанк'), ('mts', 'МТС Банк'), ('gazprombank', 'Газпромбанк'), ('vtb', 'ВТБ'), ('akbars', 'Ак Барс')], default='tinkoff', max_length=20)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('limit_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='authapp.user')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
    ]
