# Generated by Django 5.1.5 on 2025-10-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Вывод'), ('transfer', 'Перевод'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка'), ('escrow_release', 'Разблокировка эскроу')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='authapp.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
            options={
                'db_table': 'transaction_logs',
            },
        ),
    ]
