# Generated by Django 5.1.5 on 2025-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deals_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество сделок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='escrow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Эскроу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Оборот'),
        ),
    ]
