# Generated by Django 5.1.5 on 2025-02-04 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_exchangerate_p2p_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('account_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер счета')),
                ('owner_name', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('limit_transactions_per_day', models.PositiveIntegerField(default=0, verbose_name='Лимит количества заявок в сутки')),
                ('limit_amount_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Лимит суммы пополнений в сутки')),
                ('current_transactions', models.PositiveIntegerField(default=0, verbose_name='Количество использованных заявок')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма использованного лимита')),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общий оборот')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('auto_disable_on_limit', models.BooleanField(default=False, verbose_name='Автоотключение при превышении лимита')),
                ('notify_on_disable', models.BooleanField(default=False, verbose_name='Уведомление об отключении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='authapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
    ]
