# Generated by Django 5.1.5 on 2025-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bank',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('sber', 'Сбербанк'), ('mts', 'МТС Банк')], default='tinkoff', max_length=20),
        ),
    ]
