# Generated by Django 5.1.5 on 2025-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_wallet_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('sber', 'Сбербанк'), ('mts', 'МТС Банк'), ('gazprombank', 'Газпромбанк'), ('vtb', 'ВТБ'), ('akbars', 'Ак Барс')], default='tinkoff', max_length=20),
        ),
    ]
