# Generated by Django 5.1.5 on 2025-02-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_wallet_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='extra_fee',
        ),
        migrations.AddField(
            model_name='bid',
            name='extra_fee_usdt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Надбавка в USDT'),
        ),
    ]
