# Generated by Django 5.1.5 on 2025-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_bid_extra_fee_bid_extra_fee_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='extra_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
