# Generated by Django 5.1.5 on 2025-02-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_depositrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='wallet_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.depwallet'),
        ),
    ]
