# Generated by Django 5.1.5 on 2025-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_depwallet_alter_depositrequest_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depwallet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
