# Generated by Django 5.1.5 on 2025-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_depwallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='expiration_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
