# Generated by Django 5.1.5 on 2025-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_remove_depositrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
